services:
  - type: web
    name: student-management-app
    env: java
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/SpringMongoProject-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/.java
